# production
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: elliot-certificate-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: support@elliot.store
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
    # dns01:
    #   providers:
    #   - name: clouddns
    #     clouddns:
    #       serviceAccountSecretRef:
    #         name: clouddns-service-account
    #         key: ecominate-cloud-dns-sa.json
    #       project: ecominate-230617